### PR TITLE
Update Herbarium 2022

### PR DESCRIPTION
**Pull request by johnypark**
Hello,

I added the current year's competition page to the repo.

### CODE REVIEW

**Review by kiatchuan — APPROVED** [review]

**Review by johnypark — COMMENTED** [review]
.

**Comment by johnypark** [comment]
@kiatchuan, thank you for reviewing. What else process is needed to merge this pull request to visipedia?

**Comment by kiatchuan** [comment]
Apologies, forgot to merge it. It should be merged now.

**Comment by johnypark** [comment]
> Apologies, forgot to merge it. It should be merged now.

Thank you, Kiat!

**Pull request merged**
